### ISSUE TITLE
JavaScript console errors about $(...).matchHeight

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#90]
```
vendor.bundle.js:13742 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
jquery-3.1.1.slim.min.js:2 jQuery.Deferred exception: $(...).matchHeight is not a function TypeError: $(...).matchHeight is not a function
    at HTMLDocument.<anonymous> (http://localhost:4200/:47:67)
    at j (https://code.jquery.com/jquery-3.1.1.slim.min.js:2:30164)
    at k (https://code.jquery.com/jquery-3.1.1.slim.min.js:2:30478)
    at ZoneDelegate.ac_polyfills../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:16383:31)
    at Zone.ac_polyfills../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:16186:47)
    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:16436:38)
    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:17547:25) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.slim.min.js:2
k @ jquery-3.1.1.slim.min.js:2
ac_polyfills../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:16383
ac_polyfills../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:16186
ZoneTask.invoke @ polyfills.bundle.js:16436
data.args.(anonymous function) @ polyfills.bundle.js:17547
main.bundle.js:88405 Logging in with client fabric8 scope user:full and issuer https://int.rdu2c.fabric8.io:8443
main.bundle.js:88451 has valid OAuth token!
main.bundle.js:94419 Logged in with token true
main.bundle.js:88451 has valid OAuth token!
polyfills.bundle.js:16190 Uncaught TypeError: $(...).matchHeight is not a function
    at HTMLDocument.<anonymous> (http://localhost:4200/:47:67)
    at j (https://code.jquery.com/jquery-3.1.1.slim.min.js:2:30164)
    at k (https://code.jquery.com/jquery-3.1.1.slim.min.js:2:30478)
    at ZoneDelegate.ac_polyfills../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:16383:31)
    at Zone.ac_polyfills../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:16186:47)
    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:16436:38)
    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:17547:25)
(anonymous) @ :4200/:47
j @ jquery-3.1.1.slim.min.js:2
k @ jquery-3.1.1.slim.min.js:2
ac_polyfills../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:16383
ac_polyfills../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:16186
ZoneTask.invoke @ polyfills.bundle.js:16436
data.args.(anonymous function) @ polyfills.bundle.js:17547
main.bundle.js:92733 WARNING: invoked the isOpenShift() method before the APIsStore has loaded!
```

**Comment by joshuawilson** [comment]
This is a jQuery related error. I left jQuery in but we are still seeing these errors. I think it would be better if we can get away from jQuery and find another way to do the same thing.
